address: localhost:8844

placeholder-message:
  starting: "&6起動中"
  online:
    status: "&a&lオンライン (稼働中)"
    playerscount: "&f&l参加人数: &b&l%s人"
    version: "&f&lバージョン: &b&l%s"
  offline:
    status: "&6オフライン (停止中)"

# プレイヤーにサーバーのステータスを知らせる
messageStatus:
  switch: true

  # ステータスメッセージのカスタム
  message:
    starting: "&6%sが起動中です。"
    started: "&a%sが起動しました。"
    closed: "&c%sが終了しました。"

  # 特定のサーバーのステータスを知らせる場合
  # filterをtrueにし、知らせたいサーバーの名前を記述してください
  filter: false
  filter-list: