name: StatusReporter
version: '1.0.0'
main: org.luke.statusReporter.StatusReporter
description: Report status to ServerManager plugin
api-version: '1.21'
author: Luke0630
load: STARTUP

commands:
  statusreporter:
    aliases:
      - status